# -*- coding: utf-8 -*-
"""2025NS01066_MLAssignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8thXdP3CAvUcfAYg8F3kJaBDNoTwyEo

# Import Libraries
"""

!pip install -q scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection   import train_test_split, learning_curve
from sklearn.preprocessing     import LabelEncoder, StandardScaler
from sklearn.linear_model      import LogisticRegression
from sklearn.tree              import DecisionTreeClassifier
from sklearn.ensemble          import (RandomForestClassifier,
                                        GradientBoostingClassifier,
                                        VotingClassifier)
from sklearn.svm               import SVC
from sklearn.neural_network    import MLPClassifier
from sklearn.metrics           import (accuracy_score, precision_score,
                                        recall_score, f1_score,
                                        confusion_matrix,
                                        classification_report)

sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 110
print('Libraries loaded successfully.')

"""# Load Dataset"""

from google.colab import files

print('Click the button below and upload StudentPerformance_Dataset.csv')
uploaded = files.upload()
print('File uploaded:', list(uploaded.keys()))

df = pd.read_csv('/content/StudentPerformance_Dataset.csv')
df.head()

print('Class distribution:')
counts = df['Pass'].value_counts()
for label, count in counts.items():
    print(f'  {"Pass" if label==1 else "Fail"} ({label}) : {count} students ({count/len(df)*100:.1f}%)')

"""# Data Preprocessing
## Impute Missing values
"""

print('Missing values per column:')
print(df.isnull().sum())

"""## Encode Categorical Variable"""

df_processed = df.copy()
le = LabelEncoder()
df_processed['Internet_Usage'] = le.fit_transform(df_processed['Internet_Usage'])

print('Encoding applied:', dict(zip(le.classes_, le.transform(le.classes_))))

"""## Features and Target - Split"""

X = df_processed.drop('Pass', axis=1)
y = df_processed['Pass']

"""## Train & Test Split (80/20)"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""## Feature Scaling"""

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

"""# Exploratory Data Analysis (EDA)
## Distribution - Pass vs Fail
"""

fig, ax = plt.subplots(figsize=(6, 4))

counts = df['Pass'].value_counts()
bars = ax.bar(['Fail (0)', 'Pass (1)'], counts.values,
                    color=['#e74c3c', '#2ecc71'], edgecolor='white', width=0.5)
for bar, val in zip(bars, counts.values):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+5,
                 str(val), ha='center', fontweight='bold', fontsize=12)
ax.set_title('Pass vs Fail — Count', fontweight='bold')
ax.set_ylabel('Number of Students')
ax.set_ylim(0, 650)

plt.suptitle('Target Variable Distribution', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Correlation Heatmap"""

fig, ax = plt.subplots(figsize=(9, 6))

sns.heatmap(
    df_processed.corr(), annot=True, fmt='.2f',
    cmap='coolwarm', center=0, ax=ax,
    linewidths=0.5, annot_kws={'size': 9}
)
ax.set_title('Feature Correlation Heatmap', fontsize=13, fontweight='bold', pad=12)
plt.tight_layout()
plt.show()


print('Correlation with Pass (target):')
print(df_processed.corr()['Pass'].drop('Pass').sort_values(ascending=False).round(3).to_string())

"""## Boxplots - Pass vs Fail"""

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
axes = axes.flatten()

num_feats = ['Study_Hours','Attendance','Previous_Marks','Assignment_Score','Sleep_Hours']
for i, feat in enumerate(num_feats):
    bp = axes[i].boxplot(
        [df[df['Pass']==0][feat], df[df['Pass']==1][feat]],
        labels=['Fail', 'Pass'],
        patch_artist=True,
        medianprops=dict(color='black', linewidth=2.5)
    )
    bp['boxes'][0].set_facecolor('#e74c3c')
    bp['boxes'][1].set_facecolor('#2ecc71')

    for j, grp in enumerate([df[df['Pass']==0][feat], df[df['Pass']==1][feat]]):
        axes[i].plot(j+1, grp.mean(), 'D', color='white', markersize=7, zorder=5,
                     markeredgecolor='black', markeredgewidth=1)
    axes[i].set_title(feat.replace('_', ' '), fontweight='bold', fontsize=10)
    axes[i].set_ylabel('Value')

axes[5].axis('off')
axes[5].text(0.5, 0.5, 'Diamond (◆) = Mean\nBox = IQR\nLine = Median',
             ha='center', va='center', fontsize=10,
             bbox=dict(boxstyle='round,pad=0.5', facecolor='lightyellow', edgecolor='gray'))

fig.suptitle('Feature Distributions — Pass vs Fail', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Pass Rate Analysis (For all 7 features)"""

def pass_rate_bar(ax, series_x, series_pass, title, x_labels=None):
    '''Plots pass rate (%) per category with count labels.'''
    df_tmp = pd.DataFrame({'x': series_x, 'pass': series_pass})
    grp = df_tmp.groupby('x')['pass'].agg(['mean','count']).reset_index()
    labels = x_labels if x_labels else grp['x'].astype(str).tolist()
    pass_rates = grp['mean'].values * 100
    counts     = grp['count'].values
    avg        = series_pass.mean() * 100

    colors = plt.cm.RdYlGn(pass_rates / 100)
    bars = ax.bar(labels, pass_rates, color=colors, edgecolor='white', linewidth=1.2)
    for bar, rate, cnt in zip(bars, pass_rates, counts):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1.5,
                f'{rate:.0f}%', ha='center', va='bottom', fontsize=8, fontweight='bold')
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()/2,
                f'n={cnt}', ha='center', va='center', fontsize=7,
                color='white', fontweight='bold')
    ax.axhline(y=avg, color='navy', linestyle='--', linewidth=1.3,
               alpha=0.8, label=f'Overall avg: {avg:.1f}%')
    ax.set_title(title, fontweight='bold', fontsize=9)
    ax.set_ylabel('Pass Rate (%)', fontsize=8)
    ax.set_ylim(0, 90)
    ax.legend(fontsize=7)
    ax.tick_params(axis='x', labelsize=7.5)

fig, axes = plt.subplots(3, 3, figsize=(16, 13))
axes = axes.flatten()

# Attendance
att_bins = pd.cut(df['Attendance'], bins=[38,55,65,75,85,100])
pass_rate_bar(axes[0], att_bins.astype(str), df['Pass'], 'Attendance Range vs Pass Rate')

# Previou_Marks
pm_bins = pd.cut(df['Previous_Marks'], bins=[0,40,55,65,80,101])
pass_rate_bar(axes[1], pm_bins.astype(str), df['Pass'], 'Previous Marks Range vs Pass Rate')

# Assignment_Score
as_bins = pd.cut(df['Assignment_Score'], bins=[0,40,55,65,80,101])
pass_rate_bar(axes[2], as_bins.astype(str), df['Pass'], 'Assignment Score Range vs Pass Rate')

# Study_Hours
pass_rate_bar(axes[3], df['Study_Hours'], df['Pass'], 'Study Hours vs Pass Rate')

# Sleep_Hours
pass_rate_bar(axes[4], df['Sleep_Hours'], df['Pass'], 'Sleep Hours vs Pass Rate')

# Internet-Usage
pass_rate_bar(axes[5], df['Internet_Usage'], df['Pass'], 'Internet Usage vs Pass Rate')

# Extra_Coaching
pass_rate_bar(axes[6], df['Extra_Coaching'].map({0:'No',1:'Yes'}), df['Pass'],
              'Extra Coaching vs Pass Rate')

axes[7].axis('off')
axes[8].axis('off')

fig.suptitle('Pass Rate Analysis — All 7 Features', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

"""# Model Development
## Logistic Regression
"""

lr = LogisticRegression(
    random_state=42,
    max_iter=500
)
lr.fit(X_train_sc, y_train)
y_pred_lr = lr.predict(X_test_sc)
print('Logistic Regression — trained.')
print(f'  Coefficients shape: {lr.coef_.shape}')

"""## Decision Tree"""

dt = DecisionTreeClassifier(
    random_state=42,
    max_depth=5,
    criterion='gini'
)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
print('Decision Tree — trained.')
print(f'  Tree depth: {dt.get_depth()}')
print(f'  Number of leaves: {dt.get_n_leaves()}')

"""## Random Forest"""

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_features='sqrt'
)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print('Random Forest — trained.')
print(f'  Number of trees: {rf.n_estimators}')

"""## MLP/ANN (Multi-Layer Perceptron)"""

mlp = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=10
)
mlp.fit(X_train_sc, y_train)
y_pred_mlp = mlp.predict(X_test_sc)
print(f'MLP / ANN — trained in {mlp.n_iter_} epochs.')
print(f'Architecture: 7 inputs → 64 (ReLU) → 32 (ReLU) → 1 (Sigmoid)')
print(f'Final training loss: {mlp.loss_curve_[-1]:.4f}')

"""## SVM - RBF Kernel"""

svm_rbf = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True, random_state=42)
svm_rbf.fit(X_train_sc, y_train)
y_pred_svm_rbf = svm_rbf.predict(X_test_sc)
print('SVM (RBF kernel) trained.')
print(f'Support vectors: {svm_rbf.n_support_}')

"""## SVM - Linear Kernel"""

svm_lin = SVC(kernel='linear', C=0.1, class_weight='balanced',
              probability=True, random_state=42)
svm_lin.fit(X_train_sc, y_train)
y_pred_svm_lin = svm_lin.predict(X_test_sc)
print('SVM (Linear kernel) trained.')
print(f'Support vectors: {svm_lin.n_support_}')

"""## Gradient Boosting (Boosting ensemble)"""

gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1,
                                 max_depth=3, random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)
print('Gradient Boosting trained.')

"""## Voting Ensemble (RF + GB + SVM)"""

voting = VotingClassifier(
    estimators=[
        ('rf',  RandomForestClassifier(n_estimators=100, random_state=42)),
        ('gb',  GradientBoostingClassifier(n_estimators=100, random_state=42)),
        ('svm', SVC(kernel='rbf', probability=True, random_state=42)),
    ],
    voting='soft'
)
voting.fit(X_train_sc, y_train)
y_pred_voting = voting.predict(X_test_sc)
print('Voting Ensemble (RF + GB + SVM) trained.')

"""# Training & Learning Curves"""

train_sizes = np.linspace(0.1, 1.0, 8)

def plot_lc(ax, estimator, X_data, y_data, title, color):
    tr_sz, tr_sc, cv_sc = learning_curve(
        estimator, X_data, y_data, cv=5,
        train_sizes=train_sizes, scoring='accuracy'
    )
    ax.plot(tr_sz, tr_sc.mean(axis=1), 'o-', color=color, lw=2.2, label='Train Accuracy')
    ax.fill_between(tr_sz, tr_sc.mean(axis=1)-tr_sc.std(axis=1),
                           tr_sc.mean(axis=1)+tr_sc.std(axis=1), alpha=0.12, color=color)
    ax.plot(tr_sz, cv_sc.mean(axis=1), 's--', color='#e74c3c', lw=2, label='Validation Accuracy')
    ax.fill_between(tr_sz, cv_sc.mean(axis=1)-cv_sc.std(axis=1),
                           cv_sc.mean(axis=1)+cv_sc.std(axis=1), alpha=0.12, color='#e74c3c')
    ax.set_title(title, fontweight='bold', fontsize=10)
    ax.set_xlabel('Training Set Size'); ax.set_ylabel('Accuracy')
    ax.set_ylim(0.30, 0.85); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

fig, axes = plt.subplots(3, 3, figsize=(16, 13))
axes = axes.flatten()

plot_lc(axes[0], LogisticRegression(random_state=42,max_iter=500),
        X_train_sc, y_train, 'Logistic Regression', '#3498db')

plot_lc(axes[1], DecisionTreeClassifier(random_state=42,max_depth=5),
        X_train, y_train, 'Decision Tree', '#e67e22')

plot_lc(axes[2], RandomForestClassifier(n_estimators=50,random_state=42),
        X_train, y_train, 'Random Forest', '#27ae60')

plot_lc(axes[3], SVC(kernel='rbf',C=1.0,probability=True,random_state=42),
        X_train_sc, y_train, 'SVM (RBF Kernel)', '#e74c3c')

plot_lc(axes[4], SVC(kernel='linear',C=0.1,class_weight='balanced',probability=True,random_state=42),
        X_train_sc, y_train, 'SVM (Linear Kernel)', '#9b59b6')

plot_lc(axes[5], GradientBoostingClassifier(n_estimators=50,random_state=42),
        X_train, y_train, 'Gradient Boosting', '#f39c12')

epochs = list(range(1, len(mlp.loss_curve_)+1))
axes[6].plot(epochs, mlp.loss_curve_, 'o-', color='#e74c3c', lw=2.5, ms=5, label='Training Loss')
if hasattr(mlp,'validation_scores_') and mlp.validation_scores_:
    axes[6].plot(range(1,len(mlp.validation_scores_)+1),
                 [1-s for s in mlp.validation_scores_],
                 's--', color='#3498db', lw=2, ms=5, label='Validation Loss')
axes[6].set_title('MLP/ANN — Loss per Epoch', fontweight='bold', fontsize=10)
axes[6].set_xlabel('Epoch'); axes[6].set_ylabel('Loss')
axes[6].legend(fontsize=8); axes[6].grid(True, alpha=0.3)

axes[7].plot(gb.train_score_, 'o-', color='#f39c12', lw=2.5, ms=3, label='GB Train Score')
axes[7].set_title('Gradient Boosting — Score per Tree', fontweight='bold', fontsize=10)
axes[7].set_xlabel('Number of Trees'); axes[7].set_ylabel('Training Score')
axes[7].legend(fontsize=8); axes[7].grid(True, alpha=0.3)

axes[8].axis('off')
axes[8].text(0.5,0.5,
    'Interpreting Learning Curves\n\n'
    'Train >> Val  → Overfitting\n'
    'Both low      → Underfitting\n'
    'Train ≈ Val   → Well-fitted\n\n'
    'Shaded band = ±1 std (5-fold CV)',
    ha='center', va='center', fontsize=10,
    bbox=dict(boxstyle='round,pad=0.6', facecolor='lightyellow', edgecolor='#aaa'))

fig.suptitle('Training & Learning Curves — All 8 Models', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout(); plt.show()

"""# Model Evaluation"""

def get_model_metrics(y_true, y_pred, name):
    return {
        'Model': name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred),
        'F1-Score': f1_score(y_true, y_pred)
    }

metrics_data = []
metrics_data.append(get_model_metrics(y_test, y_pred_lr, 'LR'))
metrics_data.append(get_model_metrics(y_test, y_pred_dt, 'DT'))
metrics_data.append(get_model_metrics(y_test, y_pred_rf, 'RF'))
metrics_data.append(get_model_metrics(y_test, y_pred_mlp, 'MLP / ANN'))
metrics_data.append(get_model_metrics(y_test, y_pred_svm_rbf, 'SVM (RBF)'))
metrics_data.append(get_model_metrics(y_test, y_pred_svm_lin, 'SVM (Linear)'))
metrics_data.append(get_model_metrics(y_test, y_pred_gb, 'GB'))
metrics_data.append(get_model_metrics(y_test, y_pred_voting, 'VE'))

metrics_df = pd.DataFrame(metrics_data).set_index('Model')

print('Summary of Model Evaluation Metrics:')
display(metrics_df.style.format('{:.2%}'))

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
colors = ['#3498db', '#e67e22', '#2ecc71', '#9b59b6']

for i, metric in enumerate(metrics_to_plot):
    sns.barplot(x=metrics_df.index, y=metrics_df[metric], ax=axes[i], palette='viridis', hue=metrics_df.index, legend=False)
    axes[i].set_title(f'{metric} Comparison', fontweight='bold')
    axes[i].set_ylabel(metric)
    axes[i].set_xlabel('')
    axes[i].set_ylim(0, 1)
    for container in axes[i].containers:
        axes[i].bar_label(container, fmt='%.2f', fontsize=9)

fig.suptitle('Model Performance Comparison', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""### Confusion Matrices"""

def plot_confusion_matrix(ax, y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='viridis', cbar=False, ax=ax,
                xticklabels=['Fail', 'Pass'], yticklabels=['Fail', 'Pass'])
    ax.set_title(f'{model_name} - Confusion Matrix', fontweight='bold', fontsize=11)
    ax.set_xlabel('Predicted Label')
    ax.set_ylabel('True Label')

fig, axes = plt.subplots(3, 3, figsize=(15, 12))
axes = axes.flatten()

plot_confusion_matrix(axes[0], y_test, y_pred_lr, 'Logistic Regression')
plot_confusion_matrix(axes[1], y_test, y_pred_dt, 'Decision Tree')
plot_confusion_matrix(axes[2], y_test, y_pred_rf, 'Random Forest')
plot_confusion_matrix(axes[3], y_test, y_pred_mlp, 'MLP / ANN')
plot_confusion_matrix(axes[4], y_test, y_pred_svm_rbf, 'SVM (RBF Kernel)')
plot_confusion_matrix(axes[5], y_test, y_pred_svm_lin, 'SVM (Linear Kernel)')
plot_confusion_matrix(axes[6], y_test, y_pred_gb, 'Gradient Boosting')
plot_confusion_matrix(axes[7], y_test, y_pred_voting, 'Voting Ensemble')

axes[8].axis('off')

fig.suptitle('Confusion Matrices for All Models', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""# Feature Importance"""

rf_imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=True)
gb_imp = pd.Series(gb.feature_importances_, index=X.columns).sort_values(ascending=True)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
for ax, (imp, title, color) in zip(axes, [
    (rf_imp, 'Random Forest', '#27ae60'),
    (gb_imp, 'Gradient Boosting', '#e67e22')
]):
    bars = ax.barh(imp.index, imp.values, color=color, edgecolor='white')
    for bar, val in zip(bars, imp.values):
        ax.text(val+0.002, bar.get_y()+bar.get_height()/2, f'{val:.3f}', va='center', fontsize=9)
    ax.set_title(f'Feature Importance — {title}', fontweight='bold')
    ax.set_xlabel('Importance Score')
    ax.axvline(x=1/7, color='navy', ls='--', alpha=0.5, label='Equal baseline (1/7)')
    ax.legend()
plt.suptitle('RF vs Gradient Boosting Feature Importance', fontsize=13, fontweight='bold')
plt.tight_layout(); plt.show()

print('\nRank | Feature             | RF Score | GB Score')
print('-'*55)
for i,(feat,rf_v,gb_v) in enumerate(
    sorted(zip(X.columns, rf.feature_importances_, gb.feature_importances_),
           key=lambda x: -x[1]), 1):
    print(f'  {i}  | {feat:20s}| {rf_v:.4f}   | {gb_v:.4f}')

"""# Save Model (for Streamlit App)"""

import pickle

artifacts = {
    'models': {
        'Logistic Regression': lr,
        'Decision Tree':       dt,
        'Random Forest':       rf,
        'SVM (RBF)':           svm_rbf,
        'SVM (Linear)':        svm_lin,
        'Gradient Boosting':   gb,
        'Voting Ensemble':     voting,
        'MLP / ANN':           mlp,
    },
    'scaler':        scaler,
    'label_encoder': le,
    'feature_names': list(X.columns),
    'metrics_df':    mdf,
    'rf_importance': pd.Series(rf.feature_importances_, index=X.columns),
    'gb_importance': pd.Series(gb.feature_importances_, index=X.columns),
}

with open('model_artifacts.pkl', 'wb') as f:
    pickle.dump(artifacts, f)

from google.colab import files
files.download('model_artifacts.pkl')
print('model_artifacts.pkl downloaded — upload this to Streamlit app.')

"""# Predictions"""

new_student = pd.DataFrame({
    'Study_Hours': [3], 'Attendance': [55], 'Previous_Marks': [40],
    'Assignment_Score': [35], 'Sleep_Hours': [5],
    'Internet_Usage': [le.transform(['High'])[0]], 'Extra_Coaching': [0]
})
new_sc = scaler.transform(new_student)

print('Prediction for at-risk student (low attendance, low scores):\n')
model_list = [
    ('Logistic Regression', lr,      True),
    ('Decision Tree',       dt,      False),
    ('Random Forest',       rf,      False),
    ('SVM (RBF)',           svm_rbf, True),
    ('SVM (Linear)',        svm_lin, True),
    ('Gradient Boosting',   gb,      False),
    ('Voting Ensemble',     voting,  True),
    ('MLP / ANN',           mlp,     True),
]
for name, model, use_sc in model_list:
    data = new_sc if use_sc else new_student
    pred = model.predict(data)[0]
    prob = model.predict_proba(data)[0]
    print(f'  {name:25s}  {"PASS" if pred==1 else "FAIL"}   '
          f'(Fail: {prob[0]*100:.1f}%  Pass: {prob[1]*100:.1f}%)')